<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite id="0" name="C:\Users\test\Desktop\Frame\__tests__\testTransactions.js" errors="0" package="C:\Users\test\Desktop\Frame\__tests__\testTransactions.js" hostname="localhost" tests="5" failures="1" time="1.219" timestamp="2022-07-21T09:22:49">
    <properties>
    </properties>
    <testcase classname="TX signing" name="Request APPROVED" time="0">
      <failure message="Error: no valid connection
    at WebDriver2.get seleniumDriver [as seleniumDriver] (C:\Users\test\Desktop\Frame\node_modules\selenium-appium\src\Driver.ts:206:11)
    at WebDriver2.wait (C:\Users\test\Desktop\Frame\node_modules\selenium-appium\src\Driver.ts:23:17)
    at Object.&lt;anonymous&gt; (C:\Users\test\Desktop\Frame\__tests__\testTransactions.js:80:22)
    at Object.asyncJestTest (C:\Users\test\Desktop\Frame\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
    at C:\Users\test\Desktop\Frame\node_modules\jest-jasmine2\build\queueRunner.js:45:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\test\Desktop\Frame\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
    at C:\Users\test\Desktop\Frame\node_modules\jest-jasmine2\build\queueRunner.js:75:41" type="AssertionError">
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>